### ISSUE TITLE
endDate 끝난 활동 가져오는 문제

### ISSUE THREAD

**Issue by kuum97** [Gila-part4/Gila#158]

**Comment by sj0724** [comment]
리스트에서 endDate가 지나도 두는게 좋을 것 같습니다. 당근마켓에서도 판매된 제품은 판매완료로 표시되는것처럼 저희가 리스트를 최신기준으로 가져오고 있어서 문제될게 없을 것 같네요 전체적으로 회색으로 스타일링 해주면 될것 같습니다.

**Comment by kuum97** [comment]
당근마켓의 경우 기간이 정해지지 않은 판매활동이구 저희는 특정 기간에 대한 예약이기 때문에 지난 예약은 지워주는게 맞다고 판단되는데 어떻게 생각하시나요??

**Comment by sj0724** [comment]
저희가 채팅까지 구현한다고 했을때 단체가 아니라 1대1 채팅까지 한다면 지금 등록되지 않아도 전에 했던 활동이 있으면 등록한 사람에게 연락해볼수 있지 않을까요? 내가 잘 모르는 곳에 간다고 했을때 지난 활동이 남아있으면 참고할수도 있구요!
