### ISSUE TITLE
채팅관련 서드파티 서비스 적용

### ISSUE THREAD

**Issue by kuum97** [Gila-part4/Gila#182]

**Comment by sj0724** [comment]
![2024-08-22_4 38 20](https://github.com/user-attachments/assets/e76968b1-a9df-492e-9851-8a28bf46a681)
현재 채팅까지는 가능한데 채팅정보에 clientId가 들어갑니다. 이외의 정보는 넣어줄수가 없는데 그러면 유저 닉네임 표기하기에 좀 불편하네요. 닉네임 중복 방지가 있으면 쉽게 구현가능할듯 합니다.
