### ISSUE TITLE
스타일 방향성 잡기

### ISSUE THREAD

**Issue by kuum97** [Gila-part4/Gila#206]
테일윈드 css 기반으로 공통 컴포넌트 구성하여 css 관련 코드 개선

**Comment by kuum97** [comment]
- [x] 하단 네비게이션 사이드 메뉴로 개선
- [x] 대시보드 카드 테이블 개선
- [x] 각 버튼 공통화하여 코드 개선

**Comment by jinho0941** [comment]
어우 되게 열심히 하시내요 ㄷㄷ 
화이팅입니다.
