### ISSUE TITLE
회원가입 form 리팩토링

### ISSUE THREAD

**Issue by sj0724** [Gila-part4/Gila#213]
이메일 인증을 하면서 인풋마다 조건이 달라서 상당히 로직이 지저분하네요 map함수로 돌리는 것보다 일일히 input설정해주는게 유지보수하기 좋을듯 합니다.

**Comment by kuum97** [comment]
일단 해당 컴포넌트 버튼은 지금 만들어서 pr에 올려져 있는데 세부 버튼들 코드 수정이 좀 많을거같아 draft로 해두었습니다! 작업하실때 버튼은 안건드셔도 되요!

**Comment by sj0724** [comment]
로그인, 회원가입 스타일 수정도 해야합니다.

**Comment by sj0724** [comment]
일단 회원가입 로직 분리시켜놨습니다~아무래도 하나로 합치기엔 어려울듯 하네요
