### ISSUE TITLE
my-activity 활동 생성 오류

### ISSUE THREAD

**Issue by Batrnan** [Gila-part4/Gila#65]
![image](https://github.com/user-attachments/assets/baf2892f-b986-430d-9499-28f03b2f5d6c)

- 데이터를 넣고 제출을 누를 때 가끔 생성이 안됨.
- 세부사항에 아무 값도 집어넣지 않고 제출을 눌러도 활동 생성이됨.

**Comment by sj0724** [comment]
세부사항에 아무 값 없을때 제출안되도록 프론트에서 방지 어려운가요?

**Comment by kuum97** [comment]
해결완료
